import Vue from "vue";
import { library } from "@fortawesome/fontawesome-svg-core";

import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";

import {
  faUserFriends,
  faArrowLeft,
  faEllipsisH,
  faCog,
  faChevronDown,
  faSearch,
  faCheckSquare,
  faBirthdayCake,
  faCheckCircle,
  faRetweet,
  faHome,
  faHashtag,
  faBell,
  faEnvelope,
  faBookmark,
  faUserCircle,
  faUser,
  faListAlt,
  faLayerGroup,
  faFilm,
  faPollH,
  faPoll,
  faMapMarkerAlt,
  faFeatherAlt,
  faPlus,
} from "@fortawesome/free-solid-svg-icons";

import {
  faCalendarAlt,
  faCircle,
  faComment,
  faHeart,
  faShareSquare,
  faBell as faBellRegular,
  faEnvelope as faEnvelopeRegular,
  faBookmark as faBookmarkRegular,
  faListAlt as faListAltRegular,
  faUserCircle as faUserCircleRegular,
  faUser as faUserRegular,
  faImage,
  faSmile,
} from "@fortawesome/free-regular-svg-icons";

import { faTwitter } from "@fortawesome/free-brands-svg-icons";
library.add(
  faUserFriends,
  faArrowLeft,
  faEllipsisH,
  faCog,
  faChevronDown,
  faSearch,
  faCheckSquare,
  faCircle,
  faBirthdayCake,
  faCalendarAlt,
  faMapMarkerAlt,
  faComment,
  faRetweet,
  faHeart,
  faShareSquare,
  faCheckCircle,
  faTwitter,
  faHome,
  faHashtag,
  faBell,
  faBellRegular,
  faEnvelope,
  faEnvelopeRegular,
  faBookmark,
  faBookmarkRegular,
  faListAlt,
  faListAltRegular,
  faUserCircle,
  faUserCircleRegular,
  faUser,
  faUserRegular,
  faLayerGroup,
  faImage,
  faPoll,
  faFilm,
  faSmile,
  faPollH,
  faFeatherAlt,
  faPlus
);
Vue.component("f-icon", FontAwesomeIcon);
